### ISSUE TITLE
Question: Combining with Amazon S3

### ISSUE THREAD

**Issue by Dayjo** [cam861/convertapi-node#1]
Hi,

Thanks for this lovely little module. Trying to decide whether or not to use it, currently using PHP for this, but would like to move towards Node.

I'm just wondering if you have tried / had any experience sending a file from S3 and writing back to AWS S3 using the node SDK? Would like to stick it all on a Lambda and take any of the file handling away from the server as with large (40mb) pdf files and converting them to PPTX (120+mb) the server gets pretty unhappy. 

If not, no worries, I may give it a bash anyway.

Regards,

Joel

**Comment by cam861** [comment]
Hey Joel,

Apologies for the slow reply!! 

I use this in a few applications to read files (typically .docx) from S3, convert to PDF and then push back through to a different bucket.  Is use the AWS SDK for S3 - it's simple enough.  This Convert API is pretty handy as your server isn't doing the grunt work - just waits for the result. 

I haven't played with it in a Lambda, but given that it bills per ms, this could get expensive considering a conversion can take a few seconds.

Cheers,

Cam

**Comment by Dayjo** [comment]
@cam861 Lambdas are pretty cheap to run, plus I we'd probably not being doing a large number of conversions. 

In your applications, how have you been reading and sending off to the api and 'pushing back' to s3? I thought that the library only took a filePath. Are you downloading from s3 to the server, sending it, downloading the new one to the server, then writing that back to s3?

**Comment by cam861** [comment]
That's correct - I'm downloading to the server and then using the S3 SDK to putObject

It's probably not the quickest/most optimal solution.  I would guess there's a way to take the stream from ConvertAPI and stream it directly to S3. I haven't looked into that side of it very closely at all tbh.

**Comment by Dayjo** [comment]
Yeah that's what I was hoping, basically being able to stream direct from S3, or give the API a URL to go 'get' the file. I too, now have it working (for the most part) downloading to the server first and uploading.
